### ISSUE TITLE
Build fails with version 4

### ISSUE THREAD

**Issue by sonicoder86** [blacksonic/angular2-aot-webpack#81]
After updating to latest Angular beta-8 and Typescript 2.2.1 `ngc` run fails with 
```
TypeError: Cannot read property 'toJSON' of undefined
    at Object.sourceMapGeneratorToConsumerWithFileName (/home/blacksonic/workspace/ng2-aot/node_modules/tsickle/build/src/source_map_utils.js:65:42)
    at TsickleCompilerHost.combineSourceMaps (/home/blacksonic/workspace/ng2-aot/node_modules/tsickle/build/src/tsickle_compiler_host.js:135:74)
    at TsickleCompilerHost.writeFile (/home/blacksonic/workspace/ng2-aot/node_modules/tsickle/build/src/tsickle_compiler_host.js:83:28)
    at Object.writeFile (/home/blacksonic/workspace/ng2-aot/node_modules/typescript/lib/typescript.js:64240:132)
    at Object.writeFile (/home/blacksonic/workspace/ng2-aot/node_modules/typescript/lib/typescript.js:9020:14)
    at printSourceFileOrBundle (/home/blacksonic/workspace/ng2-aot/node_modules/typescript/lib/typescript.js:61197:20)
    at emitSourceFileOrBundle (/home/blacksonic/workspace/ng2-aot/node_modules/typescript/lib/typescript.js:61155:21)
    at Object.forEachEmittedFile (/home/blacksonic/workspace/ng2-aot/node_modules/typescript/lib/typescript.js:8986:17)
    at Object.emitFiles (/home/blacksonic/workspace/ng2-aot/node_modules/typescript/lib/typescript.js:61137:12)
    at emitWorker (/home/blacksonic/workspace/ng2-aot/node_modules/typescript/lib/typescript.js:64294:33)
```

Can be reproduced on v4 branch.

https://github.com/angular/angular/issues/14383

**Comment by tonimitrevski** [comment]
in tsconfig.json i remove  "mapRoot": "", and now work fine

**Comment by sonicoder86** [comment]
Fixed by https://github.com/blacksonic/angular2-aot-webpack/pull/90
